### ISSUE TITLE
Postgres adapter: is it correct to drop the table?

### ISSUE THREAD

**Issue by m-burst** [diamondio/better-queue-sql#2]
With postgres adapter, when the store is closed, the table is dropped. As far as I understand, this is not correct because the table might contain some tasks to process later or it might be in use by other node instances (if run in a replicated environment).

Could you please check this?

**Comment by m-burst** [comment]
And as I see from the code, the SQlite adapter does not drop the table.

**Comment by leanderlee** [comment]
I think you are right, it seems weird that it's dropping the table.

**Comment by jknielse** [comment]
Ditto

**Comment by m-burst** [comment]
And maybe it also should not delete the stored function either, as (again) other instances can be using it.

**Comment by nronnei** [comment]
Any progress on these issues? Asking for a friend.

**Comment by leanderlee** [comment]
Published in 1.0.2
